# Generated by Django 5.0.6 on 2024-06-20 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_customer_idx_firstname_lastname'),
    ]

    operations = [
        # Requires 2 Arguments One for Database Upgrade and @2nd for Database Downgrade (Revert Migration)

        migrations.RunSQL("""
                            INSERT INTO store_collection (title)   
                            values ('colelction1');
                          """,
                                                
                          """
                            DELETE FROM store_collection where title = "colelction1";
                          """
                          
                          )        
        
    ]
 